# Generated by Django 5.1.3 on 2024-11-26 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualizada')),
                ('ativo', models.DateField(default=True, verbose_name='Ativo')),
                ('servico', models.CharField(max_length=100, verbose_name='Servico')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descrição')),
                ('icone', models.CharField(choices=[('lni-log', 'Engrenagens'), ('lni-starts-up', 'Gráfica'), ('lni-users', 'Usuários'), ('lni-layers', 'Design'), ('lni-mobile', 'Mobile'), ('lni-rocker', 'Foguete')], max_length=100, verbose_name='Icone')),
            ],
            options={
                'verbose_name': 'Servico',
                'verbose_name_plural': 'Servicos',
            },
        ),
        migrations.DeleteModel(
            name='Servicos',
        ),
    ]
