# Generated by Django 5.1.3 on 2024-11-27 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_precos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Precos',
            new_name='Preco',
        ),
    ]
